In [1]:
#element assessing row/col
#loc and iloc--->loc and index loc based

In [7]:
import pandas as pd
df=pd.DataFrame({"name":['pinky','pop','push','pups'],
                 "rol-numbers":[401,402,403,30],
                 "branch":["cse","ece","eee","civil"]},index=[1,2,3,4])


In [8]:
df

name  rol-numbers branch
1  pinky          401    cse
2    pop          402    ece
3   push          403    eee
4   pups           30  civil

In [9]:
df.loc[1]

name           pinky
rol-numbers      401
branch           cse
Name: 1, dtype: object

In [11]:
df.loc[2]['rol-numbers']

402

In [12]:
df.iloc[3]

name            pups
rol-numbers       30
branch         civil
Name: 4, dtype: object

In [13]:
df.iloc[2]["branch"]

'eee'

In [14]:
df.info()#.....>inbuilts form

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 3 columns):
name           4 non-null object
rol-numbers    4 non-null int64
branch         4 non-null object
dtypes: int64(1), object(2)
memory usage: 288.0+ bytes


In [15]:
df.describe()

rol-numbers
count     4.000000
mean    309.000000
std     186.001792
min      30.000000
25%     308.250000
50%     401.500000
75%     402.250000
max     403.000000

In [16]:
df.count()

name           4
rol-numbers    4
branch         4
dtype: int64

In [17]:
df.dtypes

name           object
rol-numbers     int64
branch         object
dtype: object

In [19]:
df.count(axis='rows')  #rows=colum count #axis=0 coloumns

name           4
rol-numbers    4
branch         4
dtype: int64

In [20]:
df.count(axis='columns')

1    3
2    3
3    3
4    3
dtype: int64

In [21]:
df.count(axis=0)

name           4
rol-numbers    4
branch         4
dtype: int64

In [27]:
df.set_index(["rol-numbers"]) #we can set any coliumns as a index

name branch
rol-numbers              
401          pinky    cse
402            pop    ece
403           push    eee
30            pups  civil

In [26]:
df.set_index(["branch"])

name  rol-numbers
branch                    
cse     pinky          401
ece       pop          402
eee      push          403
civil    pups           30

In [31]:
import numpy as np
frame=pd.Series([9,12,3,5,4])
frame

0     9
1    12
2     3
3     5
4     4
dtype: int64

In [32]:
frame.isnull()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [33]:
frame.count()

5

In [35]:
frame.describe()

count     5.000000
mean      6.600000
std       3.781534
min       3.000000
25%       4.000000
50%       5.000000
75%       9.000000
max      12.000000
dtype: float64

In [37]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
data=pd.DataFrame(np.arange(12))

In [41]:
data

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11

In [45]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=('a','b','c'))

In [46]:
data

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [49]:
data=pd.DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))
data

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [51]:
#replace the non value to the particular ele
data.loc[1,'b']=np.nan
data

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [52]:
data.isnull()

a      b      c      d      e
0  False  False  False  False  False
1  False   True  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False

In [53]:
data.isnull().sum()

a    0
b    1
c    0
d    0
e    0
dtype: int64

In [54]:
df

name  rol-numbers branch
1  pinky          401    cse
2    pop          402    ece
3   push          403    eee
4   pups           30  civil

In [55]:
df+data

a   b branch   c   d   e name  rol-numbers
0 NaN NaN    NaN NaN NaN NaN  NaN          NaN
1 NaN NaN    NaN NaN NaN NaN  NaN          NaN
2 NaN NaN    NaN NaN NaN NaN  NaN          NaN
3 NaN NaN    NaN NaN NaN NaN  NaN          NaN
4 NaN NaN    NaN NaN NaN NaN  NaN          NaN

In [59]:
dd=df.add(data)
dd

a   b branch   c   d   e name  rol-numbers
0 NaN NaN    NaN NaN NaN NaN  NaN          NaN
1 NaN NaN    NaN NaN NaN NaN  NaN          NaN
2 NaN NaN    NaN NaN NaN NaN  NaN          NaN
3 NaN NaN    NaN NaN NaN NaN  NaN          NaN
4 NaN NaN    NaN NaN NaN NaN  NaN          NaN

In [57]:
dd.fill_value=1

In [60]:
dd

a   b branch   c   d   e name  rol-numbers
0 NaN NaN    NaN NaN NaN NaN  NaN          NaN
1 NaN NaN    NaN NaN NaN NaN  NaN          NaN
2 NaN NaN    NaN NaN NaN NaN  NaN          NaN
3 NaN NaN    NaN NaN NaN NaN  NaN          NaN
4 NaN NaN    NaN NaN NaN NaN  NaN          NaN

In [64]:
dd.add(data,fill_value=1) 

a     b branch     c     d     e name  rol-numbers
0   1.0   2.0    NaN   3.0   4.0   5.0  NaN          NaN
1   6.0   NaN    NaN   8.0   9.0  10.0  NaN          NaN
2  11.0  12.0    NaN  13.0  14.0  15.0  NaN          NaN
3  16.0  17.0    NaN  18.0  19.0  20.0  NaN          NaN
4   NaN   NaN    NaN   NaN   NaN   NaN  NaN          NaN

In [70]:
np.random.randn(2,6)

array([[ 0.09323746,  0.75124579,  0.71196388,  0.02444569,  1.49932581,
         0.86789283],
       [-0.38401141,  0.11954056, -0.55994924,  1.04386768,  0.14870012,
         0.41222077]])

In [71]:
np.random.rand(2,6)

array([[0.31841592, 0.57144737, 0.55322194, 0.3691839 , 0.81613566,
        0.2548817 ],
       [0.2787279 , 0.5669861 , 0.41650082, 0.28841187, 0.0799797 ,
        0.88423773]])

In [73]:
# creating data frame with random values
r=pd.DataFrame(np.random.randn(3,4))#,index=[])
r

0         1         2         3
0 -1.045788 -0.137135  0.085538 -2.071498
1  0.905250  1.543489 -0.625012 -1.669006
2 -1.152982 -1.217109 -0.639130  1.836534

In [74]:
r=pd.DataFrame(np.random.randn(3,4),index=['a','b','c'],
               columns=['s1','s2','s3','s4'])
r

s1        s2        s3        s4
a -0.249338 -0.910914 -0.928154 -1.184723
b  2.006858  1.018951  1.017150  0.853189
c -2.220889  1.890078  1.151742  1.088636

In [76]:
r.index=['a','b','c']
r

s1        s2        s3        s4
a -0.249338 -0.910914 -0.928154 -1.184723
b  2.006858  1.018951  1.017150  0.853189
c -2.220889  1.890078  1.151742  1.088636

In [79]:
#reindexing
r1=r.reindex(['b','a','c','d'])
r1

s1        s2        s3        s4
b  2.006858  1.018951  1.017150  0.853189
a -0.249338 -0.910914 -0.928154 -1.184723
c -2.220889  1.890078  1.151742  1.088636
d       NaN       NaN       NaN       NaN

In [80]:
r1.isnull()

s1     s2     s3     s4
b  False  False  False  False
a  False  False  False  False
c  False  False  False  False
d   True   True   True   True

In [81]:
r1.isnull().sum()

s1    1
s2    1
s3    1
s4    1
dtype: int64

In [82]:
r1.dropna() #filling drop val

s1        s2        s3        s4
b  2.006858  1.018951  1.017150  0.853189
a -0.249338 -0.910914 -0.928154 -1.184723
c -2.220889  1.890078  1.151742  1.088636

In [84]:
r1.fillna(1) #filling null values

s1        s2        s3        s4
b  2.006858  1.018951  1.017150  0.853189
a -0.249338 -0.910914 -0.928154 -1.184723
c -2.220889  1.890078  1.151742  1.088636
d  1.000000  1.000000  1.000000  1.000000

In [89]:
r1.fillna(method='bfill',axis=0).fillna(1) 

s1        s2        s3        s4
b  2.006858  1.018951  1.017150  0.853189
a -0.249338 -0.910914 -0.928154 -1.184723
c -2.220889  1.890078  1.151742  1.088636
d  1.000000  1.000000  1.000000  1.000000

In [90]:
r1.fillna(method='ffill',axis=0).fillna(1) 

s1        s2        s3        s4
b  2.006858  1.018951  1.017150  0.853189
a -0.249338 -0.910914 -0.928154 -1.184723
c -2.220889  1.890078  1.151742  1.088636
d -2.220889  1.890078  1.151742  1.088636

In [91]:
r1.isnull()

s1     s2     s3     s4
b  False  False  False  False
a  False  False  False  False
c  False  False  False  False
d   True   True   True   True

In [96]:
pd.isna(r1['s1'])

b    False
a    False
c    False
d     True
Name: s1, dtype: bool

In [97]:
# data replacing
r1

s1        s2        s3        s4
b  2.006858  1.018951  1.017150  0.853189
a -0.249338 -0.910914 -0.928154 -1.184723
c -2.220889  1.890078  1.151742  1.088636
d       NaN       NaN       NaN       NaN

In [98]:
r1.replace(0.2345456,978676)

s1        s2        s3        s4
b  2.006858  1.018951  1.017150  0.853189
a -0.249338 -0.910914 -0.928154 -1.184723
c -2.220889  1.890078  1.151742  1.088636
d       NaN       NaN       NaN       NaN

In [101]:
df33=pd.DataFrame({11:[3,3,2],12:[7,5,3],13:[9,8,0]})
df33

11  12  13
0   3   7   9
1   3   5   8
2   2   3   0

In [104]:
df33.replace(2,999)

11  12  13
0    3   7   9
1    3   5   8
2  999   3   0

In [106]:
df33.replace([32,2,1],(111,222,11))

11  12  13
0    3   7   9
1    3   5   8
2  222   3   0

In [109]:
r2=r1.reindex(['a','b','c','d'])
r2
#r1

s1        s2        s3        s4
a -0.249338 -0.910914 -0.928154 -1.184723
b  2.006858  1.018951  1.017150  0.853189
c -2.220889  1.890078  1.151742  1.088636
d       NaN       NaN       NaN       NaN

In [110]:
r1.sort_index()

s1        s2        s3        s4
a -0.249338 -0.910914 -0.928154 -1.184723
b  2.006858  1.018951  1.017150  0.853189
c -2.220889  1.890078  1.151742  1.088636
d       NaN       NaN       NaN       NaN

In [111]:
r1.columns=['s4','s2','s1','s5']
r1

s4        s2        s1        s5
b  2.006858  1.018951  1.017150  0.853189
a -0.249338 -0.910914 -0.928154 -1.184723
c -2.220889  1.890078  1.151742  1.088636
d       NaN       NaN       NaN       NaN

In [112]:
r1.sort_index(axis=1)

s1        s2        s4        s5
b  1.017150  1.018951  2.006858  0.853189
a -0.928154 -0.910914 -0.249338 -1.184723
c  1.151742  1.890078 -2.220889  1.088636
d       NaN       NaN       NaN       NaN

# groupby

In [116]:
animal_df=pd.DataFrame({'name':['dog','cat','cow','pee'],
                        'place':['austraila','panda','cat','ooo'],
                        'feature':['yellow','s1','s3','z4']})
animal_df

name      place feature
0  dog  austraila  yellow
1  cat      panda      s1
2  cow        cat      s3
3  pee        ooo      z4

In [117]:
animal_df.groupby('name').sum()

place feature
name                   
cat       panda      s1
cow         cat      s3
dog   austraila  yellow
pee         ooo      z4

In [118]:
animal_df.groupby('name').count()

place  feature
name                
cat       1        1
cow       1        1
dog       1        1
pee       1        1

In [124]:
animal_df.groupby(['name','feature']).sum()


place
name feature           
cat  s1           panda
cow  s3             cat
dog  yellow   austraila
pee  z4             ooo

In [126]:
animal_df.groupby(['feature']).sum()

name      place
feature                
s1       cat      panda
s3       cow        cat
yellow   dog  austraila
z4       pee        ooo

# ranking

In [167]:
ani_df=pd.DataFrame({'name':['dog','cat','cow','pee'],
                    'place':['austraila','panda','cat','ooo'],
                    'no_legs':[4,2,2,np.nan]})


In [168]:
ani_df

name      place  no_legs
0  dog  austraila      4.0
1  cat      panda      2.0
2  cow        cat      2.0
3  pee        ooo      NaN

In [169]:
ani_df["rank1"]=ani_df['no_legs'].rank()
ani_df

name      place  no_legs  rank1
0  dog  austraila      4.0    3.0
1  cat      panda      2.0    1.5
2  cow        cat      2.0    1.5
3  pee        ooo      NaN    NaN

In [170]:
ani_df["first-rank"]=ani_df['no_legs'].rank(method="first")
ani_df

name      place  no_legs  rank1  first-rank
0  dog  austraila      4.0    3.0         3.0
1  cat      panda      2.0    1.5         1.0
2  cow        cat      2.0    1.5         2.0
3  pee        ooo      NaN    NaN         NaN

In [171]:
ani_df["max-rank"]=ani_df['no_legs'].rank(method="max")
ani_df

name      place  no_legs  rank1  first-rank  max-rank
0  dog  austraila      4.0    3.0         3.0       3.0
1  cat      panda      2.0    1.5         1.0       2.0
2  cow        cat      2.0    1.5         2.0       2.0
3  pee        ooo      NaN    NaN         NaN       NaN

In [172]:
ani_df["non-rank"]=ani_df['no_legs'].rank(na_option="bottom")
ani_df

name      place  no_legs  rank1  first-rank  max-rank  non-rank
0  dog  austraila      4.0    3.0         3.0       3.0       3.0
1  cat      panda      2.0    1.5         1.0       2.0       1.5
2  cow        cat      2.0    1.5         2.0       2.0       1.5
3  pee        ooo      NaN    NaN         NaN       NaN       4.0

In [173]:
ani_df["non-rank"]=ani_df['no_legs'].rank(pct=True)
ani_df

name      place  no_legs  rank1  first-rank  max-rank  non-rank
0  dog  austraila      4.0    3.0         3.0       3.0       1.0
1  cat      panda      2.0    1.5         1.0       2.0       0.5
2  cow        cat      2.0    1.5         2.0       2.0       0.5
3  pee        ooo      NaN    NaN         NaN       NaN       NaN

# categorise

In [176]:
data_frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
data_frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [177]:
data_frame["cc"]=data_frame['y'].astype('category')
data_frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [178]:
data_frame["cc"]

0     6
1     7
2     8
3     9
4    10
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 10]

In [180]:
data_frame["cc"].cat.categories=["good","bad","worst",
                                 "verybad",'veryyyy']
data_frame

x   y       cc
0  1   6     good
1  2   7      bad
2  3   8    worst
3  4   9  verybad
4  5  10  veryyyy

In [182]:
data_frame["cc"]=data_frame["cc"].set_categories=["good","bad","worst",
                                 "verybad",'veryyyy']
data_frame

x   y       cc
0  1   6     good
1  2   7      bad
2  3   8    worst
3  4   9  verybad
4  5  10  veryyyy

In [185]:
data_frame.sort_values('cc')

x   y       cc
1  2   7      bad
0  1   6     good
3  4   9  verybad
4  5  10  veryyyy
2  3   8    worst

In [186]:
data_frame.groupby("cc").sum()

x   y
cc            
bad      2   7
good     1   6
verybad  4   9
veryyyy  5  10
worst    3   8

In [187]:
data_frame.groupby("cc").size()

cc
bad        1
good       1
verybad    1
veryyyy    1
worst      1
dtype: int64

# reading data

In [188]:
df=pd.read_table("text.txt")
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


humera dadadsdshndfiuwhsdijsio
0                            abc
1                            123

In [189]:
df=pd.read_table("ex1.csv")
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [190]:
df=pd.read_table("ex1.csv",sep=',')
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [191]:
df=pd.read_csv("ex1.csv")
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [192]:
df=pd.read_csv("ex2.csv")
df

1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [193]:
df.head(1)

1  2  3  4  hello
0  5  6  7  8  world

In [194]:
df.tail(1)

1   2   3   4 hello
1  9  10  11  12   foo