# 1.write a pandas program to change the order of index of a given series

In [4]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


# 2.write a python program to add,subtract,multiple and divide two pandas series
## sample series:[2,4,6,8,10],[1,3,5,7,9]

In [5]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# 3. write a python program to convert a pandas module series to python list and its type

In [6]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


# 4.write a pandas program to select the rows where the score is missing i.e;is NaN
###  sample python dictionary data and list labels:
* 'waugh','yuraj','kambli','srinath','munaf'
*  'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
*  'attempts';[1,3,2,3,2,3,1,1,2,1],
* 'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
* labels=['a','b','c','d','e','f','g','h','i','j']

In [20]:
import pandas as pd
import numpy as np
exam_data={'name':['waugh','yuraj','kambli','srinath','munaf','hhhhhh','yuvjj','gajaan','khhuhai','hags'],
         'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
          'attempts':[1,3,2,3,2,3,1,1,2,1],
          'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
labels=['a','b','c','d','e','f','g','h','i','j']
s=pd.DataFrame(exam_data,index=labels)
print("missing rows:")
print(s[s['score'].isnull()])

missing rows:
      name  score  attempts qualify
d  srinath    NaN         3      no
h   gajaan    NaN         1      no


# 5 write a numpy program to create a 3x3 matrix with values ranging from 2 to 10


In [21]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# 6.illustrate the difference between ravel and flatten by taking considering multidimensional array

In [27]:
x=np.arange(2,10).reshape(2,4)
y=np.arange(1,9).reshape(2,4)
print(y.ravel())
print(x.flatten())

[1 2 3 4 5 6 7 8]
[2 3 4 5 6 7 8 9]


# 7. create a 3x3 numpy array,find out the minimum,maximum values and also their indices accordingly for each axes .also find out the statistical methods such as standard deviation,cummulative sum and product 

In [26]:
r=np.arange(2,11).reshape(3,3)
print(r)
print('min',r.min())
print('max',r.max())
print('std',r.std())
print('cumlative sum',r.cumsum())
print('cumlative product',r.cumprod())

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
min 2
max 10
std 2.581988897471611
cumlative sum [ 2  5  9 14 20 27 35 44 54]
cumlative product [      2       6      24     120     720    5040   40320  362880 3628800]


# 8. create a dataframe find out info about that dataframe adn description and sum of null values

In [29]:
df=pd.DataFrame({'name':['hi','nye','hhh','jikk'],
                 'rollno':['503',np.nan,'508','454'],
                 'branch':['cse','ece',np.nan,'eee']})
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
name      4 non-null object
rollno    3 non-null object
branch    3 non-null object
dtypes: object(3)
memory usage: 176.0+ bytes
None
       name rollno branch
count     4      3      3
unique    4      3      3
top     nye    503    cse
freq      1      1      1
name      0
rollno    1
branch    1
dtype: int64


# 9 write a pandas program to get the first 3 rows and last 2 rows of a given dataframe

In [24]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])


First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
