In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[9,8,9]])
a

array([[1, 2, 3],
       [9, 8, 9]])

In [3]:
np.shape(a)

(2, 3)

In [6]:
a[0]

array([1, 2, 3])

In [7]:
a[0,2]

3

In [8]:
a[1,1]

8

In [9]:
a

array([[1, 2, 3],
       [9, 8, 9]])

In [12]:
a[0:,0]

array([1, 9])

In [13]:
a[:,-1]

array([3, 9])

In [14]:
a[:,2]

array([3, 9])

In [19]:
a[:,0::2]

array([[1, 3],
       [9, 9]])

In [20]:
a[:,0:2]

array([[1, 2],
       [9, 8]])

In [22]:
#3d
x=np.array([[1,2,3],[9,8,9],[2,3,4]])
x

array([[1, 2, 3],
       [9, 8, 9],
       [2, 3, 4]])

In [24]:
x[1,1]

8

In [29]:
x[:,-2]

array([2, 8, 3])

In [30]:
x[0,::]

array([1, 2, 3])

In [31]:
x[:,0::2]

array([[1, 3],
       [9, 9],
       [2, 4]])

In [33]:
x[:,0]

array([1, 9, 2])

In [34]:
x.min()

1

In [35]:
x.max()

9

In [36]:
x.mean()

4.555555555555555

In [37]:
x.min(axis=0) #firstcolumn

array([1, 2, 3])

In [38]:
x.max(axis=1)

array([3, 9, 4])

In [40]:
x.sum(axis=0)

array([12, 13, 16])

In [41]:
x.sum(axis=1)

array([ 6, 26,  9])

In [42]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [3.        , 2.82842712, 3.        ],
       [1.41421356, 1.73205081, 2.        ]])

In [43]:
np.std(x)

3.02254900194121

In [44]:
a=np.array([(1,9,2),(2,3,4),(7,5,6)])

In [46]:
b=np.array([(1,9,2),(2,3,4),(7,5,6)])

In [47]:
np.vstack((a,b))

array([[1, 9, 2],
       [2, 3, 4],
       [7, 5, 6],
       [1, 9, 2],
       [2, 3, 4],
       [7, 5, 6]])

In [48]:
np.hstack((a,b))

array([[1, 9, 2, 1, 9, 2],
       [2, 3, 4, 2, 3, 4],
       [7, 5, 6, 7, 5, 6]])

In [50]:
np.ravel((a,b))

array([1, 9, 2, 2, 3, 4, 7, 5, 6, 1, 9, 2, 2, 3, 4, 7, 5, 6])

In [51]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
for i in np.arange(1,5):
    print(x)

[[1 2 3]
 [9 8 9]
 [2 3 4]]
[[1 2 3]
 [9 8 9]
 [2 3 4]]
[[1 2 3]
 [9 8 9]
 [2 3 4]]
[[1 2 3]
 [9 8 9]
 [2 3 4]]


In [53]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.41211849,  0.98935825,  0.41211849],
       [ 0.90929743,  0.14112001, -0.7568025 ]])

In [54]:
np.cos(a)

array([[ 0.54030231, -0.91113026, -0.41614684],
       [-0.41614684, -0.9899925 , -0.65364362],
       [ 0.75390225,  0.28366219,  0.96017029]])

In [55]:
np.tan(a)

array([[ 1.55740772, -0.45231566, -2.18503986],
       [-2.18503986, -0.14254654,  1.15782128],
       [ 0.87144798, -3.38051501, -0.29100619]])

# pandas

In [ ]:
pandas (data will structure will display)


In [57]:
import pandas as pd

In [58]:
#creating a series data type
s=pd.Series([1,2,3,4,5,5])
s

0    1
1    2
2    3
3    4
4    5
5    5
dtype: int64

In [63]:
s1=pd.Series([1,2,3,4,5,5],index=['x','y','z','a','b','c'])
s1

x    1
y    2
z    3
a    4
b    5
c    5
dtype: int64

In [67]:
s+s1

x     2
y     4
z     6
a     8
b    10
c    10
dtype: int64

In [128]:
v1=[1,2,3]
v2=[3,4,5]
df=pd.DataFrame({'x':v1,'y':v2})
df

x  y
0  1  3
1  2  4
2  3  5

In [127]:
df.isnull()

x1     x2     x3     x4
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False

In [75]:
#slicing
#merging and joing
#concentation
#changing the index
#changing column
#data

In [125]:
df1=pd.DataFrame({'x':[20,30,34,21],'y':[60,42,21,15]},index={'a','b','c','d'},dtype=float)

In [126]:
df1

x     y
b  20.0  60.0
c  30.0  42.0
a  34.0  21.0
d  21.0  15.0

In [139]:
data=[[2,3,3,2],[60,42,21,15],[12,34,56,78]]

In [140]:
df=pd.DataFrame(data,columns=["x1","x2",'x3','x4'])


In [141]:
df

x1  x2  x3  x4
0   2   3   3   2
1  60  42  21  15
2  12  34  56  78

In [142]:
df.isnull()

x1     x2     x3     x4
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False

In [143]:
df.values

array([[ 2,  3,  3,  2],
       [60, 42, 21, 15],
       [12, 34, 56, 78]], dtype=int64)

In [144]:
df.size

12

In [145]:
df.ndim

2

In [146]:
#slicing
df.head(2)

x1  x2  x3  x4
0   2   3   3   2
1  60  42  21  15

In [147]:
df.tail(2)

x1  x2  x3  x4
1  60  42  21  15
2  12  34  56  78

In [148]:
df.tail()

x1  x2  x3  x4
0   2   3   3   2
1  60  42  21  15
2  12  34  56  78

In [149]:
# MERGING AND JOING
df1

x1  x2  x3  x4
0   2   3   3   2
1  60  42  21  15
2  12  34  56  78

In [150]:
print(pd.merge(df1,df))     

   x1  x2  x3  x4
0   2   3   3   2
1  60  42  21  15
2  12  34  56  78


In [162]:
data=[[2,3,3,2],[60,42,21,15],[12,34,56,78]]
df1=pd.DataFrame(data,columns=["x1","x2",'x3','x4'])
df1

x1  x2  x3  x4
0   2   3   3   2
1  60  42  21  15
2  12  34  56  78

In [163]:
df

x1  x2  x3  x4
0   2   3   3   2
1  60  42  21  15
2  12  34  56  78

In [164]:
m=pd.merge(df1,df)
print(m)

   x1  x2  x3  x4
0   2   3   3   2
1  60  42  21  15
2  12  34  56  78


In [166]:
d=[[2,3,4],[4,5,6,7],[5,4,3],[7,8,9,10]]

In [167]:
f1=pd.DataFrame(d,columns=["x",'y','z','z1'],index=[1,2,3,4])

In [168]:
f1

x  y  z    z1
1  2  3  4   NaN
2  4  5  6   7.0
3  5  4  3   NaN
4  7  8  9  10.0

In [174]:
d1=[[3,4,6],[4,2,8,9],[7,8,9,10]]
f2=pd.DataFrame(d1,columns=["x",'y','z','z1'])
f2

x  y  z    z1
0  3  4  6   NaN
1  4  2  8   9.0
2  7  8  9  10.0

In [175]:
merge=pd.merge(f1,f2)

In [176]:
merge

x  y  z    z1
0  7  8  9  10.0

In [179]:
x=[[1,2,3],[4,6,7]]
f3=pd.DataFrame(x,columns=['y1','y2','y3'],index=['a','b'])

In [185]:
f3

y1  y2  y3
a   1   2   3
b   4   6   7

In [187]:
f4=pd.DataFrame({'name':[6,4,11],'gender':[10,2,8]})
f4

name  gender
0     6      10
1     4       2
2    11       8

In [188]:
joint=f3.join(f4)
joint

y1  y2  y3  name  gender
a   1   2   3   NaN     NaN
b   4   6   7   NaN     NaN

In [193]:
#concat
k=pd.concat((f3,f2))

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [194]:
k.isnull()

x      y     y1     y2     y3      z     z1
a   True   True  False  False  False   True   True
b   True   True  False  False  False   True   True
0  False  False   True   True   True  False   True
1  False  False   True   True   True  False  False
2  False  False   True   True   True  False  False

In [195]:
k.notnull()

x      y     y1     y2     y3      z     z1
a  False  False   True   True   True  False  False
b  False  False   True   True   True  False  False
0   True   True  False  False  False   True  False
1   True   True  False  False  False   True   True
2   True   True  False  False  False   True   True

In [197]:
k.columns

Index(['x', 'y', 'y1', 'y2', 'y3', 'z', 'z1'], dtype='object')

In [198]:
k["y2"]

a    2.0
b    6.0
0    NaN
1    NaN
2    NaN
Name: y2, dtype: float64

In [205]:
#indexing changing
k1=pd.DataFrame({1:[1,2,3],2:[4,5,6],'i':['x','y','z']})
k1.set_index('i')

1  2
i      
x  1  4
y  2  5
z  3  6

In [212]:
# changing the column headers
k2=k1.rename(columns={1:'a',2:'b'})
k1

1  2  i
0  1  4  x
1  2  5  y
2  3  6  z

In [216]:
dd=pd.read_csv("ex1.csv")
dd

x y z k 
0  3 4 6 7
1  3 5 8 9

In [219]:
dd['x']

KeyError: 'x'

In [223]:
dd=pd.read_csv("f.csv")
dd

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte